sudo: required
dist: trusty
language: ocaml
branches:
  only:
  - 1.0
  - /^deploy-.*$/
services:
- docker
env:
- TARGETS=build
- TARGETS=check
- TARGETS=examples
notifications:
  email:
  - tracker@easycrypt.info
before_install:
- docker pull easycryptpa/ec-build-box
after_failure:
- >-
  [ -f report.log ] && curl -sT report.log http://chunk.io/
script:
- >-
  docker run -v $PWD:/home/ci/easycrypt easycryptpa/ec-build-box
  sh -c "git clone easycrypt easycrypt.dev && cd easycrypt.dev && opam config exec -- make ${TARGETS}"
